name: Build for Linux

on:
  # Enable manual run
  workflow_dispatch:
  push:
    tags:
      - '**'

jobs:
  get-version:
    name: Get version
    runs-on: ubuntu-latest
    outputs:
      buildName: ${{ steps.get_version.outputs.buildName }}
      buildNumber: ${{ steps.get_version.outputs.buildNumber }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version
        id: get_version
        run: |
          # get buildName from pubspec.yaml (before the +)
          buildName=$(grep -oP '(?<=version: ).*(?=\+)' pubspec.yaml)
          echo "buildName=$buildName" >> $GITHUB_OUTPUT

          # get buildNumber from pubspec.yaml (after the +)
          buildNumber=$(grep -oP '(?<=version: ).*' pubspec.yaml | grep -oP '(?<=\+).*$')
          echo "buildNumber=$buildNumber" >> $GITHUB_OUTPUT

  build-flutter-app:
    name: Build Flutter app
    runs-on: ubuntu-latest
    needs: get-version
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev libsecret-1-dev libjsoncpp-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get

      - name: Build Linux portable
        run: |
          flutter build linux

      - name: Compress Flutter build
        id: compress
        run: |
          archiveName="SuperNonogram_v${{ needs.get-version.outputs.buildName }}.tar.gz"
          echo "archiveName=$archiveName" >> $GITHUB_OUTPUT

          tar -C build/linux/x64/release/bundle -cvf $archiveName .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: SuperNonogram-Archive
          path: ${{ steps.compress.outputs.archiveName }}

      - name: Upload to GitHub release
        uses: svenstaro/upload-release-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.compress.outputs.archiveName }}

  build-flatpak:
    name: Build flatpak
    runs-on: ubuntu-latest
    needs: [build-flutter-app, get-version]
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Download app archive
        uses: actions/download-artifact@v3
        with:
          name: SuperNonogram-Archive

      - name: Rename app archive
        run: |
          mv SuperNonogram_*.tar.gz SuperNonogram-Linux-Portable.tar.gz

      - name: Build .flatpak
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: SuperNonogram.flatpak
          manifest-path: flatpak/com.adilhanney.super_nonogram.json

      - name: Rename .flatpak
        id: rename
        run: |
          flatpakName="SuperNonogram_v${{ needs.get-version.outputs.buildName }}.flatpak"
          echo "flatpakName=$flatpakName" >> $GITHUB_OUTPUT

          mv SuperNonogram.flatpak $flatpakName

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Flatpak artifact
          path: ${{ steps.rename.outputs.flatpakName }}

  build-appimage:
    name: Build AppImage
    needs: [build-flutter-app, get-version]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install AppImage dependencies
        run: |
          sudo add-apt-repository universe
          sudo apt install libfuse2

      - name: Download app archive
        uses: actions/download-artifact@v3
        with:
          name: SuperNonogram-Archive

      - name: Rename app archive
        run: |
          mv SuperNonogram_*.tar.gz SuperNonogram-Linux-Portable.tar.gz

      - name: Download appimage-builder
        working-directory: appimage
        run: |
          wget -O appimage-builder-x86_64.AppImage https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.1.0/appimage-builder-1.1.0-x86_64.AppImage
          chmod +x appimage-builder-x86_64.AppImage

      - name: Prepare build files
        working-directory: appimage
        run: |
          echo 1. Extracting app archive
          mkdir AppDir
          tar -xvf ../SuperNonogram-Linux-Portable.tar.gz -C AppDir
          echo 2. Copying icons
          install -Dm644 ../assets/icon/resized/icon-16x16.png AppDir/usr/share/icons/hicolor/16x16/apps/com.adilhanney.super_nonogram.png
          install -Dm644 ../assets/icon/resized/icon-24x24.png AppDir/usr/share/icons/hicolor/24x24/apps/com.adilhanney.super_nonogram.png
          install -Dm644 ../assets/icon/resized/icon-32x32.png AppDir/usr/share/icons/hicolor/32x32/apps/com.adilhanney.super_nonogram.png
          install -Dm644 ../assets/icon/resized/icon-48x48.png AppDir/usr/share/icons/hicolor/48x48/apps/com.adilhanney.super_nonogram.png
          install -Dm644 ../assets/icon/resized/icon-64x64.png AppDir/usr/share/icons/hicolor/64x64/apps/com.adilhanney.super_nonogram.png
          install -Dm644 ../assets/icon/resized/icon-128x128.png AppDir/usr/share/icons/hicolor/128x128/apps/com.adilhanney.super_nonogram.png
          install -Dm644 ../assets/icon/resized/icon-256x256.png AppDir/usr/share/icons/hicolor/256x256/apps/com.adilhanney.super_nonogram.png
          install -Dm644 ../assets/icon/resized/icon-512x512.png AppDir/usr/share/icons/hicolor/512x512/apps/com.adilhanney.super_nonogram.png
          echo 3. Copying metadata
          install -Dm644 ../flatpak/com.adilhanney.super_nonogram.metainfo.xml AppDir/usr/share/metainfo/com.adilhanney.super_nonogram.metainfo.xml

      - name: Set AppImage version
        working-directory: appimage
        run: |
          # replace line with "version: latest" with "version: $buildName"
          sed -i "s/version: latest/version: ${{ needs.get-version.outputs.buildName }}/" AppImageBuilder.yml

      - name: Build AppImage
        working-directory: appimage
        run: |
          ./appimage-builder-x86_64.AppImage --skip-test

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: AppImage artifact
          path: appimage/SuperNonogram-*-x86_64.AppImage*

      - name: Upload to GitHub release
        uses: svenstaro/upload-release-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: appimage/SuperNonogram-*-x86_64.AppImage*
          file_glob: true
